version: '3.8'

services:
  device_db:
    image: postgres:16.2
    container_name: telemetry_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - telemetry_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  telemetry_data:

networks:
  backend:
